apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: jeus-rolebinding
 namespace: default
subjects:
 - kind: ServiceAccount
   name: jeususer
roleRef:
 kind: Role
 name: jeus-role
 apiGroup: rbac.authorization.k8s.io

